### ISSUE TITLE
Issue after node update 20 

### ISSUE THREAD

**Issue by denizka1991** [aws-actions/aws-secretsmanager-get-secrets#73]
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node16' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)

**Comment by jirkafajfr** [comment]
Can you post your workflow definition? I am especially interested in `runs-on`, does it support node 20?

In mean time can you pin the action to the `aws-actions/aws-secretsmanager-get-secrets@v1.0.4` not the latest?

**Comment by jirkafajfr** [comment]
Since this is breaking runtime change, I've released node 20 upgrade under the `2.0.0` version, the `1.x.x` will remain pinned to the node 16. Just re-running your action should fix the problem (no need to pin to the older version as suggested in previous post). I'll close the ticket now, but feel free to let us know if you still have problems.
